// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.API.Data;

#nullable disable

namespace UserManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526023203_InitialCreateWithPerfisAndSetores")]
    partial class InitialCreateWithPerfisAndSetores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserManagement.API.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador do sistema",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Funcionário do setor",
                            Nome = "Funcionário"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Gerente de operações",
                            Nome = "Gerente"
                        });
                });

            modelBuilder.Entity("UserManagement.API.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Setor de Desenvolvimento de Software",
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Setor de Gestão de Pessoas",
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Setor de Finanças e Contabilidade",
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("UserManagement.API.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLimiteFinalizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("EvidenciaUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SetorId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("SetorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserManagement.API.Models.Tarefa", b =>
                {
                    b.HasOne("UserManagement.API.Models.User", "Criador")
                        .WithMany("TarefasComoCriador")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.User", "Responsavel")
                        .WithMany("TarefasComoResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.Setor", "Setor")
                        .WithMany("Tarefas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("Responsavel");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.HasOne("UserManagement.API.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.Setor", "Setor")
                        .WithMany("Usuarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Perfil");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("UserManagement.API.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UserManagement.API.Models.Setor", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.Navigation("TarefasComoCriador");

                    b.Navigation("TarefasComoResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
