// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.API.Data;

#nullable disable

namespace UserManagement.AP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserManagement.API.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador do sistema",
                            Nome = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Funcionário do setor",
                            Nome = "Funcionário"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Gerente de operações",
                            Nome = "Gerente"
                        });
                });

            modelBuilder.Entity("UserManagement.API.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Setor de Desenvolvimento de Software",
                            Nome = "Desenvolvimento"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Setor de Gestão de Pessoas",
                            Nome = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Setor de Finanças e Contabilidade",
                            Nome = "Financeiro"
                        });
                });

            modelBuilder.Entity("UserManagement.API.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLimiteFinalizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("EvidenciaUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SetorId");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadorId = 1,
                            DataAgendamento = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 5, 26, 2, 36, 50, 156, DateTimeKind.Utc).AddTicks(513),
                            DataLimiteFinalizacao = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Verificar todos os endpoints e exemplos da documentação da API de usuários.",
                            Nome = "Revisar Documentação API V1",
                            ResponsavelId = 2,
                            SetorId = 1,
                            Status = "Agendada"
                        },
                        new
                        {
                            Id = 2,
                            CriadorId = 1,
                            DataAgendamento = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 5, 26, 2, 36, 50, 156, DateTimeKind.Utc).AddTicks(527),
                            DataLimiteFinalizacao = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Compilar dados para o relatório de progresso da equipe de desenvolvimento.",
                            Nome = "Preparar Relatório Semanal de Progresso",
                            ResponsavelId = 2,
                            SetorId = 1,
                            Status = "EmAndamento"
                        },
                        new
                        {
                            Id = 3,
                            CriadorId = 1,
                            DataAgendamento = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2025, 5, 26, 2, 36, 50, 156, DateTimeKind.Utc).AddTicks(532),
                            DataLimiteFinalizacao = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Definir e estimar tarefas para a próxima sprint do projeto X.",
                            Nome = "Planejamento da Sprint de Junho",
                            ResponsavelId = 1,
                            SetorId = 1,
                            Status = "Agendada"
                        },
                        new
                        {
                            Id = 4,
                            CriadorId = 1,
                            DataAgendamento = new DateTime(2025, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 5, 26, 2, 36, 50, 156, DateTimeKind.Utc).AddTicks(539),
                            DataLimiteFinalizacao = new DateTime(2025, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Realizar entrevistas com os candidatos finalistas para a vaga de Analista de RH.",
                            Nome = "Entrevistas Candidatos Analista RH",
                            ResponsavelId = 3,
                            SetorId = 2,
                            Status = "Agendada"
                        },
                        new
                        {
                            Id = 5,
                            CriadorId = 1,
                            DataAgendamento = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataCriacao = new DateTime(2025, 5, 26, 2, 36, 50, 156, DateTimeKind.Utc).AddTicks(542),
                            DataLimiteFinalizacao = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Preparar e apresentar os resultados financeiros do último trimestre.",
                            Nome = "Apresentar Resultados Trimestrais",
                            ResponsavelId = 1,
                            SetorId = 3,
                            Status = "Agendada"
                        });
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SetorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("SetorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserManagement.API.Models.Tarefa", b =>
                {
                    b.HasOne("UserManagement.API.Models.User", "Criador")
                        .WithMany("TarefasComoCriador")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.User", "Responsavel")
                        .WithMany("TarefasComoResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.Setor", "Setor")
                        .WithMany("Tarefas")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("Responsavel");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.HasOne("UserManagement.API.Models.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UserManagement.API.Models.Setor", "Setor")
                        .WithMany("Usuarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Perfil");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("UserManagement.API.Models.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UserManagement.API.Models.Setor", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UserManagement.API.Models.User", b =>
                {
                    b.Navigation("TarefasComoCriador");

                    b.Navigation("TarefasComoResponsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
